Lint:
  Severity: refactor

Lint/NumberConversion:
  Enabled: true

Lint/ShadowedException:
  Enabled: false

Lint/RescueException:
  Exclude:
    - 'app/lib/koala/evaluator.rb'

## New Cops
Lint/NonDeterministicRequireOrder:
  Enabled: true
