Rails:
  Enabled: true

Rails/ActiveRecordAliases:
  Enabled: false

Rails/ActiveRecordOverride:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/SaveBang:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
