RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Max: 45

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 13

RSpec/NestedGroups:
  Max: 5

RSpec/NamedSubject:
  Enabled: false

## New cops
RSpec/RepeatedExampleGroupDescription:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: true

RSpec/LeakyConstantDeclaration:
  Enabled: true
