Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'app/lib/koala/evaluator.rb'

Style/DateTime:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/lib/koala/evaluator.rb'

Style/GuardClause:
  MinBodyLength: 4

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MultilineMethodSignature:
  Enabled: true

Style/Send:
  Enabled: true
