Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Exclude:
    - 'app/lib/koala/evaluator.rb'

Style/DateTime:
  Enabled: true
  Exclude:
    - 'app/workers/sync_job.rb'

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Exclude:
    - 'app/models/namely_importer.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/lib/koala/evaluator.rb'
    - 'spec/features/**/*_spec.rb'

Style/GuardClause:
  MinBodyLength: 4

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MultilineMethodSignature:
  Enabled: true

Style/MutableConstant:
  Exclude:
    - 'app/models/net_suite/constants.rb'

Style/Send:
  Enabled: true
