require:
  - rubocop-rails

inherit_from:
  - rubocop-vanilla.yml
  - rubocop/rails.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'gen/**/*'
    - 'protorepo/**/*'
  # rubocop checks .ruby-version for version
  # TargetRubyVersion: 2.6
